### ISSUE TITLE
Position footer at base of display view

### ISSUE THREAD

**Issue by aretenz** [ManukauTramping/web-site#22]

**Comment by mathewTH** [comment]
you're looking (in particular) for
position: fixed;
bottom: 0;
it works, but I'm still looking how you make the width what you want
https://www.w3schools.com/howto/howto_css_fixed_footer.asp

**Comment by mathewTH** [comment]
bingo
```
position: fixed;
left: 0;
bottom: 0;
right: 0;
```
but you also need `container` class on the footer.
lastly you'll need some padding on the body (like it needs for navbar - hence the class) `padding-bottom: 4.5em;` seems about right. Padding prevents content being hidden behind the footer without a scrollbar.

For the body styling, take a look at my other branch to see how I changed that to fix the dom warning. actually I'll make a pr now - just for review.

**Comment by mathewTH** [comment]
this is a good start... it brings up other problems though
```
#___gatsby, #gatsby-focus-wrapper {
	height: 100vh;
}
```

**Comment by aretenz** [comment]
Fixed in attached pr
